include:
  - project: "infrastructure-engineering-shared/gitlab-ci-templates"
    file:
      - "lint_docker.yaml"
      - "build_and_scan_docker.yaml"
      - "security_scan.yaml"
      - "kubectl_commands.yaml"

variables:
  IMAGE: "tulibraries/centralized-metadata"
  HARBOR: "harbor.k8s.temple.edu"
  HELM_EXPERIMENTAL_OCI: "1"

.export_variables: &export_variables
  - source .env
  - export VERSION="${DOCKER_IMAGE_VERSION}-${CI_COMMIT_SHORT_SHA}"

before_script:
  - *export_variables

stages:
  - lint
  - build
  - tag
  - deploy

lint:
  extends: .lint_docker
  variables:
    DF: ".docker/app/Dockerfile"

build:
  stage: build
  extends: .build_and_scan_image
  variables:
    DF: ".docker/app/Dockerfile --build-arg SECRET_KEY_BASE=$SECRET_KEY_BASE --no-cache"
  except:
    - tags

tag:
  stage: tag
  extends: .tag_image

qa_deploy:
  variables:
    IMAGE: $HARBOR/tulibraries/centralized-metadata
    RANCHER: rancher-np
    CLUSTER: dev-library0
  stage: deploy
  extends: .helm_setup
  only:
    - main
  script:
    - *export_variables
    - helm pull oci://$HARBOR/tulibraries/centralized-metadata-charts/centralized-metadata --untar
    - helm upgrade centralized-metadata oci://$HARBOR/tulibraries/centralized-metadata-charts/centralized-metadata --history-max=5 --namespace=centralized-metadata-qa --values centralized-metadata/values.yaml --set image.repository=$IMAGE:$VERSION
