version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      CM_DB_HOST: db
      CM_DB_NAME: centralized_metadata
      CM_DB_PASSWORD: password
    
