version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

workflows:
  version: 2
  test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1-node
      - image: cimg/postgres:16.1

    executor: ruby/default
    environment:
      CM_DB_ADAPTOR: postgresql
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install
      - run:
          name: Set Up Database
          command: bundle exec rails db:setup
      - run:
          name: test
          command: bundle exec rake
      - run:
          name: Make sure rswag is valid
          command: bundle exec rake rswag
      - run:
          name: Check rswag build did not update anything.
          command: if [[ $(git diff) ]]; then error 1; fi
