---
openapi: 3.0.1
info:
  title: Centralized Metadata Records
  version: v1
paths:
  "/records":
    get:
      summary: list records
      tags:
      - records
      description: "This web service returns records in a JSON format. \n      The
        pagination default is set to return 25 records at a time. If you would like
        to change this,\n      add the parameter per_page=number_desired to the query
        parameters."
      responses:
        '200':
          description: successful
    post:
      summary: create record
      tags:
      - records
      description: "This web service creates a new record. There are two methods for
        adding records.\n\n      Using a curl statement: curl -F 'marc_file=@spec/fixtures/marc/louis_armstrong.mrc'
        https://centralized-metadata-qa.k8s.temple.edu \n\n      Ingest with a rake
        task: rake db:ingest[spec/fixtures/marc]."
      responses:
        '200':
          description: successful
  "/records/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show record
      tags:
      - records
      description: This web service returns an indivudual record in JSON format.
      responses:
        '200':
          description: successful
    patch:
      summary: update record
      tags:
      - records
      description: This web serive updates a record.
      responses:
        '200':
          description: successful
    put:
      summary: update record
      tags:
      - records
      description: This web serive updates a record.
      responses:
        '200':
          description: successful
    delete:
      summary: delete record
      tags:
      - records
      description: This web serive deletes a record.
      responses:
        '200':
          description: successful
servers:
- url: https://centralized-metadata-qa.k8s.temple.edu/records
  variables:
    defaultHost:
      default: https://centralized-metadata-qa.k8s.temple.edu/records
